class Functions:
    CommConnect = "CommConnect()"
    GetLoginInfo = "GetLoginInfo(QString)"
    SetInputValue = "SetInputValue(QString, QString)"
    CommRqData = "CommRqData(QString, QString, int, QString)"
    GetCommData = "GetCommData(QString, QString, int, QString)"
    GetCommRealData = "GetCommRealData(QString, QString, QString)"
    SetRealReg = "SetRealReg(QString, QString, QString, QString)"
    GetCommDataEx = "GetCommDataEx(QString, QString)"
    SendOrder = "SendOrder(QString, QString, QString, int, QString, int, int, QString, QString)"
    GetChejanData = "GetChejanData(QString)"
    DisconnectRealData = "DisconnectRealData(QString)"
